[
  # False positive from code generated by `use Gettext.Backend`; Dialyzer sees
  # Gettext/Expo plural-form internals crossing an opaque type boundary.
  {"lib/growthpush_router_web/gettext.ex", :call_without_opaque}
]
